apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-svc
  name: webserver-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    # nodePort: 30001
  selector:
    app: webserver-deploy
  type: LoadBalancer
